### ISSUE TITLE
rend="lead-tail" and rend="hook" 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/atalanta#20]
with p as content - I think it's the same character. There are 8 `lead-tail` attributes in emblem and 1 `hook` attribute in emblem 25. both look mostly like this: Ꝓ

and they all expand to `pro`. so going with "hook" in Unicode it's `p with flourish`. It's a brevigraph for "pro".

**Comment by sdigiulio** [comment]
It's not perfect, but I think that's a close match, yes. And yes, I think most of those should all be the same thing in terms of the markup, if they're not already -- especially since I think most of those are marking up abbreviated "pro".

**Comment by emylonas** [comment]
made the change
