### ISSUE TITLE
<add> used for margin notes

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/atalanta#9]
These should probably be `<note>s` . Check on anchoring attributes.

```
emblem01.xml
<add place="margin-left" >

emblem05.xml
<add place="margin-right">

emblem06.xml
<add place="margin-right">

emblem26.xml
<add place="margin-left" rend="italic">

emblem26.xml
<add place="margin-right" rend="italic">
```

**Comment by sdigiulio** [comment]
This should be fully addressed by https://github.com/Brown-University-Library/atalanta/commit/ef9b0131c59b7c43ef58ee4579c055e137c1af49, so I'm closing the issue for now.
